export type EventType =
  | "run-created"
  | "run-started"
  | "run-completed"
  | "run-failed"
  | "run-resumed"
  | "run-cancelled"
  | "run-paused"
  | "run-resumed"
  | "budget-warning"
  | "phase-started"
  | "phase-completed"
  | "phase-failed"
  | "agent-spawned"
  | "agent-heartbeat"
  | "agent-completed"
  | "agent-failed"
  | "agent-killed"
  | "agent-incomplete"
  | "agent-branch-promoted"
  | "buildplan-submitted"
  | "buildplan-approved"
  | "buildplan-rejected"
  | "contract-created"
  | "contract-updated"
  | "contract-acknowledged"
  | "contract-violated"
  | "builder-started"
  | "builder-test-pass"
  | "builder-test-fail"
  | "integration-started"
  | "integration-passed"
  | "integration-failed"
  | "evaluation-started"
  | "evaluation-passed"
  | "evaluation-failed"
  | "merge-queued"
  | "merge-lock-acquired"
  | "merge-lock-released"
  | "merge-lock-timeout"
  | "rebase-merge-result"
  | "merge-branch-clean"
  | "merge-branch-conflicted"
  | "merge-branch-conflict-resolved"
  | "merge-branch-conflict-failed"
  | "merge-branch-error"
  | "state-db-backed-up"
  | "state-db-restored"
  | "state-db-backup-removed"
  | "module-redecomposed"
  | "blocker-created"
  | "blocker-resolved"
  | "agent-blocked"
  | "agent-unblocked";

export interface EventRecord {
  id: string;
  run_id: string;
  agent_id: string | null;
  type: EventType;
  data: string | null;
  created_at: string;
}
